version: '3'
services:
  client_controller:
    build: ./server/client_controller
    ports: 
      - "8000:8000"
      - "8002:8002"
  logic:
    build: ./server/logic    
    ports:
      - "8001:8001"
      - "8003:8003"
  spotify:
    build: ./server/spotify
    ports: 
      - "8004:8004"
  utils:
    build: ./server/utils
    ports: 
      - "8005:8005"
      - "8006:8006"
  react_client:
    build: ./react_client    
    ports: 
      - "3000:3000"
